// CardResources.qml
pragma Singleton
import QtQuick
// //名字
// enum CardName {
//     Name_Begin,
//     Sha,
//     Shan,
//     Tao,
//     Jiu,
//     Huo_Sha,
//     Lei_Sha,
//     Wu_Zhongshengyou,
//     Wu_Gufengdeng,
//     Tao_yuanjieyi,
//     Wan_jianqifa,
//     Huo_Gong,
//     Nan_Manruqin,
//     Jie_Daosharen,
//     Bing_Niangchunduan,
//     Tie_Suolianhuan,
//     Le_Busishu,
//     Jue_Dou,
//     Wu_Xiekeji,
//     Zhu_Geliannv,
//     Ci_Xiongshuanggujian,
//     Han_Bingjian,
//     Fang_Tianhuaji,
//     Zhu_Queyushan,
//     Ba_Guazhen,
//     Teng_Jia,
//     Ren_Wangdun,
//     Bai_Yingshizi,
//     Fang_Yuma,
//     Jing_Gongma,
//     Guo_Hechaiqiao,
//     Shun_Shouqianyang,
//     Shan_Dian,
//     Guan_Shifu,
//     Qi_Linggong,
//     Qing_Longyanyuedao,
//     Qing_Gangjian,
//     Gu_Dingdao,
//     Zhang_Bashemao,
//     Name_End,
// };

QtObject {
    property var cardFrontImages: {
        "Sha": "qrc:/sha.webp",
        "Tao":"qrc:/tao.jpg",
        "Shan":"qrc:/shan.webp",
        "Jiu":"qrc:/jiu.jpeg",
        "Sha_Hei_Tao": "qrc:/sha.webp",
        "Sha_Hong_Tao": "qrc:/sha.webp",
        "Shan_Hei_Tao": " qrc:/sha.webp",
        "Huo_Sha":"qrc:/huosha.PNG",
        "Lei_Sha":"qrc:/leisha.PNG",
        "Wu_Zhongshengyou":"qrc:/jinnang/wuzhongshengyou.JPG",
        "Tao_yuanjieyi":"qrc:/jinnang/taoyuanjieyi.JPG",
        "Wan_jianqifa":"qrc:/jinnang/wanjianqifa.JPG",
        "Huo_Gong":"qrc:/jinnang/huogong.PNG",
        "Nan_Manruqin":"qrc:/jinnang/nanmanruqin.JPG",
        "Jie_Daosharen":"qrc:/jinnang/jiedaosharen.JPG",
        "Bing_Niangchunduan":"qrc:/jinnang/bingliangcunduan.PNG",
        "Tie_Suolianhuan":"qrc:/jinnang/tiesuolianhuan.PNG",
        "Le_Busishu":"qrc:/jinnang/lebusishu.JPG",
        "Jue_Dou":"qrc:/jinnang/juedou.webp",
        "Wu_Xiekeji":"qrc:/jinnang/wuxiekeji.JPG",
        "Zhu_Geliannv":"qrc:/zhuangbei/zhugeliannu.JPG",
        "Ci_Xiongshuanggujian":"qrc:/zhuangbei/cixiongshuanggujian.JPG",
        "Han_Bingjian":"qrc:/zhuangbei/hanbingjian.JPG",
        "Fang_Tianhuaji":"qrc:/zhuangbei/fangtianhuaji.JPG",
        "Zhu_Queyushan":"qrc:/zhuangbei/zhuqueyushan.PNG",
        "Ba_Guazhen":"qrc:/zhuangbei/baguazhen.JPG",
        "Teng_Jia":"qrc:/zhuangbei/tengjia.PNG",
        "Ren_Wangdun":"qrc:/zhuangbei/renwangdun.JPG",
        "Bai_Yingshizi":"qrc:/zhuangbei/baiyinshizi.PNG",
        "Fang_Yuma":'qrc:/zhuangbei/fangyuma.JPG',
        "Jing_Gongma":"qrc:/zhuangbei/jingongma.JPG",
        "Guo_Hechaiqiao":"qrc:/jinnang/guohechaiqiao.JPG",
        "Shun_Shouqianyang":"qrc:/jinnang/shunshouqianyang.JPG",
        "Shan_Dian":"qrc:/jinnang/shandian.JPG",
        " Guan_Shifu":"qrc:/zhuangbei/guanshifu.JPG",
        "Qi_Linggong":"qrc:/zhuangbei/qilingong.JPG",
        "Qing_Longyanyuedao":"qrc:/zhuangbei/qinglongyanyuedao.JPG",
        "Qing_Gangjian":"qrc:/zhuangbei/qinggangjian.JPG",
        "Gu_Dingdao":"qrc:/zhuangbei/gudingdao.PNG",
        "Zhang_Bashemao":"qrc:/zhuangbei/zhangbashemao.webp",
        " Wu_Gufengdeng":"qrc:/jinnang/wugufengdeng.JPG",
        " Jie_Daosharen":"qrc:/jinnang/jiedaosharen.JPG",
        // 其他卡牌图片
        "default": "qrc:/images/default.png"
    }

    property var suitColors: {
        "Hei_Tao": "qrc:/heitao.webp",
        "Hong_Tao": "qrc:/hongtao.webp",
        "Mei_Hua": "qrc:/meihua.jpg",
        "Fang_Kuai": "qrc:/fangkuai.webp"
    }
}
